version: "3"
services:
  api:
    restart: always
    ports:
    - 8080:8080
    #image: springio/demo
    build: ./
    networks:
    - backend

  web:
    restart: always
    ports:
    - 8000:8000
    #image: demo-web
    build: ../volunteering-front-end
    networks:
    - backend

  db:
    restart: always
    ports:
    - 3000:3036
    #image: demo-db
    build: ./src/main/docker/mysql
    networks:
    - backend

networks:
  backend: