version: "3"
services:
  api:
    restart: always
    ports:
    - 8080:8080
    image: springio/demo
    networks:
    - backend

  web:
    restart: always
    ports:
    - 8000:8000
    image: demo-web
    networks:
    - backend

  db:
    restart: always
    ports:
    - 3000:3036
    image: demo-db
    networks:
    - backend

networks:
  backend: