version: "2"
services:
  api:
    restart: always
    ports:
    - 8080:8080
    image: springio/demo
    networks:
    - backend

  web:
    restart: always
    ports:
    - 8000:80
    #image: demo-web
    build: ../test
    networks:
    - backend

  db:
    restart: always
    ports:
    - 3000:3306
    #image: demo-db
    build: ./src/main/docker/mysql
    networks:
    - backend

networks:
  backend: