version: "2.1"
services:
  api:
    restart: always
    ports:
    - 8080:8080
    image: springio/demo
    networks:
    - backend
    depends_on:
      db:
        condition: service_healthy

  web:
    restart: always
    ports:
    - 8000:80
    #image: demo-web
    build: ../test
    networks:
    - backend

  db:
    restart: always
    ports:
    - 3005:3306
    healthcheck:
      test: mysql --user=${USER_DB_USER:-root} --password=${USER_DB_PASSWORD:-root} -e "SELECT 1;" -N -s -r && exit 0 || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    #image: demo-db
    build: ./src/main/docker/mysql
    networks:
    - backend

networks:
  backend: