version: "2.1"
services:
  api:
    restart: always
    ports:
    - 8080:8080
    image: springio/demo
    networks:
    - backend
    depends_on:
      db:
        condition: service_healthy

  web:
    restart: always
    ports:
    - 8000:80
    #image: demo-web
    build: ../test
    networks:
    - backend

  db:
    restart: always
    ports:
    - 3005:3306
    healthcheck:
      test: mysql --user=${USER_DB_USER:-root} --password=${USER_DB_PASSWORD:-root} -e "SELECT 1;" -N -s -r && exit 0 || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    #image: demo-db
    build: ./src/main/docker/mysql
    networks:
    - backend

  andi-bot:
    image: andigital/andi-bot
    links:
    - andi-bot-redis
    ports:
    - 3000:8080
    volumes:
    - ../andi-bot/:/andi-bot
    environment:
    - HUBOT_SLACK_TOKEN=${HUBOT_SLACK_TOKEN}
    command: "bin/hubot_dev --adapter slack -r scripts/new_feature"
    networks:
    - backend

  andi-bot-redis:
    image: redis
    ports:
    - 6379:6379
    networks:
    - backend

networks:
  backend: